/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_csnd6_WRAP_H_
#define SWIG_csnd6_WRAP_H_

class SwigDirector_CsoundCallbackWrapper : public CsoundCallbackWrapper, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_CsoundCallbackWrapper(JNIEnv *jenv, Csound *csound);
    SwigDirector_CsoundCallbackWrapper(JNIEnv *jenv, CSOUND *csound);
    virtual void MessageCallback(int attr, char *msg);
    virtual double InputValueCallback(char const *chnName);
    virtual void OutputValueCallback(char const *chnName, double value);
    virtual int YieldCallback();
    virtual void MidiInputCallback(CsoundMidiInputBuffer *p);
    virtual void MidiOutputCallback(CsoundMidiOutputBuffer *p);
    virtual ~SwigDirector_CsoundCallbackWrapper();
public:
    bool swig_overrides(int n) {
      return (n < 6 ? swig_override[n] : false);
    }
protected:
    bool swig_override[6];
};


#endif
